wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.9.5
      5: 0.10.30
      8:
      - 1
      - 3
      - 5
    visualize:
      Confusion matrix (testing):
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: Confusion matrix (testing)
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Confusion matrix (testing)_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      Confusion matrix (training):
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: Confusion matrix (training)
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Confusion matrix (training)_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batchSize:
  desc: null
  value: 32
classes:
  desc: null
  value:
  - COVID
  - Lung Opacity
  - Normal
  - Viral Pneumonia
classesLen:
  desc: null
  value: 4
epochs:
  desc: null
  value: 5
fc_size_1:
  desc: null
  value: 256
fc_size_2:
  desc: null
  value: 128
fc_size_3:
  desc: null
  value: 64
fc_size_4:
  desc: null
  value: 32
fc_size_5:
  desc: null
  value: 16
fc_size_6:
  desc: null
  value: 8
inputSize:
  desc: null
  value: 256
learningRate:
  desc: null
  value: 0.0001
name:
  desc: null
  value: WithoutUpsampling_32Batch
outputSize:
  desc: null
  value: 4
upSampling:
  desc: null
  value: false
