wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.9.0
      5: 0.10.30
      8:
      - 1
      - 3
      - 5
batchSize:
  desc: null
  value: 128
classes:
  desc: null
  value:
  - COVID
  - Lung Opacity
  - Normal
  - Viral Pneumonia
classesLen:
  desc: null
  value: 4
epochs:
  desc: null
  value: 600
fc_size_1:
  desc: null
  value: 256
fc_size_2:
  desc: null
  value: 128
fc_size_3:
  desc: null
  value: 64
fc_size_4:
  desc: null
  value: 32
fc_size_5:
  desc: null
  value: 16
fc_size_6:
  desc: null
  value: 8
inputSize:
  desc: null
  value: 256
learningRate:
  desc: null
  value: 0.0001
outputSize:
  desc: null
  value: 4
upSampling:
  desc: null
  value: true
