wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    t:
      1:
      - 1
      - 5
      4: 3.9.0
      5: 0.10.29
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 500
fc_size_1:
  desc: null
  value: 128
fc_size_2:
  desc: null
  value: 64
fc_size_3:
  desc: null
  value: 32
fc_size_4:
  desc: null
  value: 16
input_dim:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0001
output_dim:
  desc: null
  value: 4
