wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      - 5
      4: 3.9.5
      5: 0.10.29
      8:
      - 1
      - 3
      - 5
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
batchSize:
  desc: null
  value: 32
classes:
  desc: null
  value:
  - COVID
  - Lung Opacity
  - Normal
  - Viral Pneumonia
classesLen:
  desc: null
  value: 4
epochs:
  desc: null
  value: 21
fc_size_1:
  desc: null
  value: 256
fc_size_2:
  desc: null
  value: 128
fc_size_3:
  desc: null
  value: 64
fc_size_4:
  desc: null
  value: 32
fc_size_5:
  desc: null
  value: 16
fc_size_6:
  desc: null
  value: 8
inputSize:
  desc: null
  value: 256
learningRate:
  desc: null
  value: 0.0001
name:
  desc: null
  value: WithoutUpsampling_32Batch
outputSize:
  desc: null
  value: 4
upSampling:
  desc: null
  value: false
